apiVersion: v1
kind: Namespace
metadata:
  labels:
  name: httpd-from-jenkins-on-k8s

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd-server
  name: httpd-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd-server
    spec:
      containers:
      - image: httpd-24
        name: httpd-24
        resources: {}
